name: Black Code Formatter

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: lgeiger/black-action@v1.0.1
        with:
          args: "custom_components/weather_data/ --check"
      - name: Flake8 Code Linter
        uses: jonasrk/flake8-action@master
        with: 
          args: "--max-line-length=120 "
